app/ToWatchList/models.py
from app.app import db


class User(db.Model):
    user_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(100), nullable=False)


class ToWatchList(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), nullable=False)
    link = db.Column(db.String(255), nullable=False)

class ToDo(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)

class Notes(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)

app/ToWatchList/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.ToWatchList.models import User, ToWatchList, ToDo, Notes
from app.app import db
from app.config import Config


to_watch_list = Blueprint("to_watch_list", __name__, template_folder="templates")


@to_watch_list.route("/", methods=["GET"])
def index():
    to_watch_items = ToWatchList.query.all()
    to_do_items = ToDo.query.all()
    notes_items = Notes.query.all()

    return render_template("index.html", to_watch_items=to_watch_items, to_do_items=to_do_items, notes_items=notes_items)


@to_watch_list.route("/delete/<int:item_id>", methods=["POST"])
def delete_to_watch_item(item_id):
    item = ToWatchList.query.get(item_id)
    db.session.delete(item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))

@to_watch_list.route("/create", methods=["POST"])
def create_to_watch_item():
    title = request.form["title"]
    link = request.form["link"]

    new_item = ToWatchList(title=title, link=link)
    db.session.add(new_item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))

@to_watch_list.route("/delete_todo/<int:item_id>", methods=["POST"])
def delete_to_do_item(item_id):
    item = ToDo.query.get(item_id)
    db.session.delete(item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))

@to_watch_list.route("/create_todo", methods=["POST"])
def create_to_do_item():
    content = request.form["content"]

    new_item = ToDo(content=content)
    db.session.add(new_item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))


@to_watch_list.route("/delete_notes/<int:item_id>", methods=["POST"])
def delete_notes_item(item_id):
    item = Notes.query.get(item_id)
    db.session.delete(item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))

@to_watch_list.route("/create_notes", methods=["POST"])
def create_notes_item():
    content = request.form["content"]

    new_item = Notes(content=content)
    db.session.add(new_item)
    db.session.commit()

    return redirect(url_for("to_watch_list.index"))

app/ToWatchList/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Default title{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
    {% block script%}
    {% endblock %}
</body>
</html>

app/ToWatchList/templates/delete_btn.html
<button class="delete-btn">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 69 14"
    class="svgIcon bin-top"
  >
    <g clip-path="url(#clip0_35_24)">
      <path
        fill="black"
        d="M20.8232 2.62734L19.9948 4.21304C19.8224 4.54309 19.4808 4.75 19.1085 4.75H4.92857C2.20246 4.75 0 6.87266 0 9.5C0 12.1273 2.20246 14.25 4.92857 14.25H64.0714C66.7975 14.25 69 12.1273 69 9.5C69 6.87266 66.7975 4.75 64.0714 4.75H49.8915C49.5192 4.75 49.1776 4.54309 49.0052 4.21305L48.1768 2.62734C47.3451 1.00938 45.6355 0 43.7719 0H25.2281C23.3645 0 21.6549 1.00938 20.8232 2.62734ZM64.0023 20.0648C64.0397 19.4882 63.5822 19 63.0044 19H5.99556C5.4178 19 4.96025 19.4882 4.99766 20.0648L8.19375 69.3203C8.44018 73.0758 11.6746 76 15.5712 76H53.4288C57.3254 76 60.5598 73.0758 60.8062 69.3203L64.0023 20.0648Z"
      ></path>
    </g>
    <defs>
      <clipPath id="clip0_35_24">
        <rect fill="white" height="14" width="69"></rect>
      </clipPath>
    </defs>
  </svg>

  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 69 57"
    class="svgIcon bin-bottom"
  >
    <g clip-path="url(#clip0_35_22)">
      <path
        fill="black"
        d="M20.8232 -16.3727L19.9948 -14.787C19.8224 -14.4569 19.4808 -14.25 19.1085 -14.25H4.92857C2.20246 -14.25 0 -12.1273 0 -9.5C0 -6.8727 2.20246 -4.75 4.92857 -4.75H64.0714C66.7975 -4.75 69 -6.8727 69 -9.5C69 -12.1273 66.7975 -14.25 64.0714 -14.25H49.8915C49.5192 -14.25 49.1776 -14.4569 49.0052 -14.787L48.1768 -16.3727C47.3451 -17.9906 45.6355 -19 43.7719 -19H25.2281C23.3645 -19 21.6549 -17.9906 20.8232 -16.3727ZM64.0023 1.0648C64.0397 0.4882 63.5822 0 63.0044 0H5.99556C5.4178 0 4.96025 0.4882 4.99766 1.0648L8.19375 50.3203C8.44018 54.0758 11.6746 57 15.5712 57H53.4288C57.3254 57 60.5598 54.0758 60.8062 50.3203L64.0023 1.0648Z"
      ></path>
    </g>
    <defs>
      <clipPath id="clip0_35_22">
        <rect fill="white" height="57" width="69"></rect>
      </clipPath>
    </defs>
  </svg>
</button>

app/ToWatchList/templates/index.html
{% extends "base.html" %}
{% block title %}To Watch List{% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="to-watch-container">
            <h2>To Watch List</h2>
            <il>
                {% for item in to_watch_items %}
                    <li class="to-watch-item">
                        <a href="{{ item.link }}" target="_blank">{{ item.title }}</a>
                        <form action="{{ url_for('to_watch_list.delete_to_watch_item', item_id=item.id) }}" method="POST">
                            {% include "delete_btn.html" %}
                        </form>
                    </li>
                {% endfor %}
            </il>
        
            <form method="POST" class="form" action="{{ url_for('to_watch_list.create_to_watch_item') }}">
                <input class = "inputFrom" type="text" name="title" placeholder="Enter the title">
                <input class = "inputFrom" type="text" name="link" placeholder="Enter the link">
                <button class="form-btn" type="submit">
                    <span class="circle1"></span>
                    <span class="circle2"></span>
                    <span class="circle3"></span>
                    <span class="circle4"></span>
                    <span class="circle5"></span>
                    <span class="text">Submit</span>
                </button>
            </form>
        </div>
        
        <div class="to-do-container">
            <h2>To Do List</h2>
            <div id="checklist">
                {% for i in to_do_items %}
                    <input value="{{ loop.index }}" id="0{{ loop.index }}" name="r" type="checkbox">
                    <label for="0{{ loop.index }}">{{ i.content }}</label>
                {% endfor %}
            </div>

            <form method="POST" class="form" action="{{ url_for('to_watch_list.create_to_do_item') }}">
                <input class = "inputFrom" type="text" name="content" placeholder="Enter the content">
                <button class="form-btn" type="submit">
                    <span class="circle1"></span>
                    <span class="circle2"></span>
                    <span class="circle3"></span>
                    <span class="circle4"></span>
                    <span class="circle5"></span>
                    <span class="text">Submit</span>
                </button>
            </form>

        </div>

        <div class="notes-container">
            <h2>Notes</h2>
            <il>
                {% for item in notes_items %}
                    <li class="notes-item">
                        <textarea>{{ item.content }}</textarea>
                        <form action="{{ url_for('to_watch_list.delete_notes_item', item_id=item.id) }}" method="POST">
                            {% include "delete_btn.html" %}
                        </form>
                    </li>
                {% endfor %}
            </il>

            <form method="POST" class="form" action="{{ url_for('to_watch_list.create_notes_item') }}">
                <textarea class="notes-input" placeholder="Enter your notes here..." name="content"></textarea>
                <button class="form-btn" type="submit">
                    <span class="circle1"></span>
                    <span class="circle2"></span>
                    <span class="circle3"></span>
                    <span class="circle4"></span>
                    <span class="circle5"></span>
                    <span class="text">Submit</span>
                </button>
            </form>
        </div>

    </div>
    
    
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}